### ISSUE TITLE
EnumerateStackReferences(ClrThread thread, bool includeDead) includeDead is true

### ISSUE THREAD

**Issue by jerzy-d** [Microsoft/clrmd#89] opened 2017-10-23 23:44 UTC
I found something which might be an issue in MDR.
I written a WPF utility, using this library, to examine crush dumps from our clients.
One the recent dumps had multitude of threads, and many of them have invalid 
StackBase (0), and StackLimit (0). But the few have Stack limit of 5,062,380,473,975,767,040, and one, 
with a valid stack base, has also this enormous stack limit.
In my utility I am using EnumerateStackReferences twice, with includeDead = false and then true, we looking at the dead stack objects too. The call to EnumerateStackReferences(ClrThread thread, bool includeDead) will attempt to loop (when inspecting stack memory) about 633 quadrillion times.
The call with includedDead false is of course fine.
I fixed that on our side, by checking for this condition, but maybe it can be fixed in MDR?
BTW.
Thank you for this exellent library. We are going very often thru our customers crash dumps, and I got tired of writting compilcated WinDbg scripts. My utility became quite popular among developers in my company, and what most important, my boss can't live without it.
It is not quite ready for public release, but if you care I can point you to my github account.
Thank you Jerzy.

**Comment by leculver** [comment] 2019-01-03 01:38
Thank you for the bug report!  Sorry it's taken me so long to do something here.

Unfortunately the real root of the problem is that we've calculated the stack base/limit incorrectly.  I don't know of any way to reproduce this issue.  I've checked in a workaround to limit the damage in this scenario.  Please let me know if you have a repro (or crash dump) that exhibits this problem you could share and I'll take a look at the underlying issue.

**Closed by leculver** 2019-01-03 01:38 UTC
