### ISSUE TITLE
Unable to load DLL 'dbgeng.dll': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)

### ISSUE THREAD

**Issue by dudikeleti** [Microsoft/clrmd#78] opened 2017-06-01 17:30 UTC
Note: There is already an [issue ](https://github.com/Microsoft/clrmd/issues/29) similar to this but it's pretty old and its closed.

ClrMD version: 0.8.31.0
.NET Framework: 4.5.1
Architecture: 86 and 64
OS: Windows 10

dbgeng.dll exist in c:\windows\system32 (also dbgcore and dbghelp if it matter)

When I call `DataTarget.AttachToProcess(id, milliseconds, AttachFlag.NonInvasive)` I got this error every time.

> Unable to load DLL 'dbgeng.dll': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)

Stack trace:

    at Microsoft.Diagnostics.Runtime.Desktop.NativeMethods.DebugCreate(Guid& InterfaceId, Object& Interface)
    at Microsoft.Diagnostics.Runtime.DbgEngDataReader.CreateIDebugClient()
    at Microsoft.Diagnostics.Runtime.DbgEngDataReader..ctor(Int32 pid, AttachFlag flags, UInt32 msecTimeout)
    at Microsoft.Diagnostics.Runtime.DataTarget.AttachToProcess(Int32 pid, UInt32 msecTimeout, AttachFlag attachFlag)

**Comment by cklutz** [comment] 2017-06-30 16:45
I just had the same issue. I added a possible [workaround](https://github.com/Microsoft/clrmd/issues/29#issuecomment-312316730) to the original issue.

**Comment by dudikeleti** [comment] 2017-08-09 13:45
@cklutz Thanks for the comment. Now I got the error on "mrt100dac_winamd64.dll". Any idea?

**Comment by leculver** [comment] 2017-08-10 16:32
I'm not quite sure what to do with this one.  I may end up adding a more descriptive error message when it happens.

I specifically don't specify where to load dbgeng.dll to let the application developer choose which one to load specifically (as with the workaround cklutz posted).  I do this very often myself using a more up to date version than what's shipped in system32.

**Comment by leculver** [comment] 2018-11-19 21:12
Hello! This issue is being closed due to its age. The codebase has moved significantly since this was filed. Please feel free to open a new issue for ClrMD about this issue if it still reproduces on ClrMD 1.0. (Also, I apologize for having not looked at or resolved this earlier and for resolving it now. In order for me to be able to make some progress on the growing issue count in ClrMD I need to clear the backlog down to a manageable set of issues, but do feel free to file a new one if this is still a problem.)

Please @leculver if you reply to this message to make sure I get it.

**Closed by leculver** 2018-11-19 21:12 UTC
