### ISSUE TITLE
Multi Attach not working

### ISSUE THREAD

**Issue by Alois-xx** [Microsoft/clrmd#60] opened 2017-01-23 22:41 UTC
DataTarget behaves strange when I attach to more than one processes at a time. The returned heaps from both processes are identical which cannot be. 
Wrong:
D:\Source\git\clrmd\src>D:\Source\git\clrmd\src\MultiAttach\bin\Debug\MultiAttach.exe 15728 7832
Heap: ClrHeap 22.434048mb 3 segments, Heap2: ClrHeap 22.434048mb 3 segments

Expected:
D:\Source\git\clrmd\src>D:\Source\git\clrmd\src\MultiAttach\bin\Debug\MultiAttach.exe 15728 7832
Heap: ClrHeap 110.382284mb 8 segments, Heap2: ClrHeap 22.434048mb 3 segments

Source: 
```
using Microsoft.Diagnostics.Runtime;
using System;

namespace MultiAttach
{
    class Program
    {
        static void Main(string[] args)
        {
            DataTarget t2 = null;

            var t1 = DataTarget.AttachToProcess(int.Parse(args[0]), 5000);

            try
            {
                ClrHeap heap2 = null;

                var runtime1 = t1.ClrVersions[0].CreateRuntime();
                //var heap = runtime1.GetHeap(); // this works strangely

                if (args.Length > 1)
                {
                    t2 = DataTarget.AttachToProcess(int.Parse(args[1]), 5000);
                    var runtime2 = t2.ClrVersions[0].CreateRuntime();
                    heap2 = runtime2.GetHeap();
                }

                var heap = runtime1.GetHeap(); // this returns the same heap!!!!

                Console.WriteLine($"Heap: {heap}, Heap2: {heap2}");
            }
            finally
            {
                if (t1 != null)
                    t1.Dispose();
                if (t2 != null)
                    t2.Dispose();
            }
        }
    }
}
```

**Comment by leculver** [comment] 2018-11-19 17:52
Hello!  This issue is being closed due to its age.  The codebase has moved significantly since this was filed.  Please feel free to open a new issue for ClrMD about this issue if it still reproduces on ClrMD 1.0.  (Also, I apologize for having not looked at or resolved this earlier and for resolving it now.  In order for me to be able to make some progress on the growing issue count in ClrMD I need to clear the backlog down to a manageable set of issues, but do feel free to file a new one if this is still a problem.)

**Closed by leculver** 2018-11-19 17:52 UTC
