### ISSUE TITLE
Cancellation support and timeouts for symbol servers

### ISSUE THREAD

**Issue by jazzdelightsme** [Microsoft/clrmd#4] opened 2015-09-22 16:57 UTC
Waiting for network timeouts can be a major bummer. It would be great if we could:
1. Add overloads that take System.Threading.CancellationTokens.
2. Add support for configurable timeouts (shorter than network timeout by default?).
3. Async support would be icing on the cake.

Some comments from Lee:

> In addition to cancellation support, we also need to have a timeout for SymbolLocator.  I’m not sure if it should be an individual timeout (for slow individual servers) or a global timeout when calling FindBinary/FindPdb (such that after N seconds the operation is cancelled) or both.  Keep in mind that calling virtually any function in ClrMD may go out to the symbol server to download files if we are missing metadata that we need to perform an operation.
> 
> Also it’d be really nice if ClrMD could support some modern features like async/await…especially for symbol servers.

**Comment by leculver** [comment] 2015-09-24 05:35
I have implemented async/await additions to ClrMD, along with adding a timeout to SymbolLocator.  Unfortunately HttpWebRequest does not accept cancellation tokens, so I'm not sure there's an easy way to use one here.

**Comment by zodiacon** [comment] 2015-09-24 06:18
You could use HttpClient instead - it's all async.

**Comment by leculver** [comment] 2015-09-24 17:01
Good point.  I won't be able to get to it until next week, but I'll add CancellationToken support to the todo list.

**Comment by leculver** [comment] 2018-11-19 17:50
Hello!  This issue is being closed due to its age.  The codebase has moved significantly since this was filed.  Please feel free to open a new issue for ClrMD about this issue if it still reproduces on ClrMD 1.0.  (Also, I apologize for having not looked at or resolved this earlier and for resolving it now.  In order for me to be able to make some progress on the growing issue count in ClrMD I need to clear the backlog down to a manageable set of issues, but do feel free to file a new one if this is still a problem.)

**Closed by leculver** 2018-11-19 17:50 UTC
Labels: enhancement
