### ISSUE TITLE
Array types are not returned by ClrHeap.EnumerateTypes()

### ISSUE THREAD

**Issue by JeffCyr** [Microsoft/clrmd#114] opened 2018-07-19 19:43 UTC
Array types are not returned by ClrHeap.EnumerateTypes() if ClrHeap.GetObjectType(...) wasn't called yet.

As a workaround, you can call ClrHeap.CacheHeap(...), then the array types will be present in EnumerateTypes. But this can be time consuming in large memory dump.

**Comment by leculver** [comment] 2018-12-22 18:50
I think this is By Design.  Or "By Poor Design".

EnumerateTypes should really not exist...it's basically "enumerate types we've seen", which is a really bad thing to have in an API design:  We should have either not enumerated any array types at all or we should have enumerated every type's array type...

I plan to rework a lot of ClrMD's internals in 1.2 (which is a ways out).  Rethinking what we do with EnumerateTypes is one of the things to do...  I'm going to close this issue for now I think.

If there's a scenario you are targeting maybe it would help to describe that more to make sure it's covered.  If you can describe what you are doing with EnumerateTypes I may file an issue specifically to clean up that scenario.

**Closed by leculver** 2018-12-22 18:50 UTC

**Comment by JeffCyr** [comment] 2018-12-27 00:20
Alright, my use case was to have a `EnumerateObjects(string typeName)` which supports wildcards.

It was more efficient to run the regex once per type with `EnumerateTypes` then comparing the `ClrType` reference in `EnumerateObjects` instead of running the regex for all object instances
