### ISSUE TITLE
PEFile utilities have buffering issues

### ISSUE THREAD

**Issue by weltkante** [Microsoft/clrmd#51] opened 2016-10-24 10:47 UTC
- In PEFile::GetPdbSignature there is a 'break' instruction which skips freeing the buffer cache
- The current cache size is 1 buffer, but this method uses 2 at the same time. You may want to consider increasing your cache size to 2 to cover the common case.

https://github.com/Microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/Utilities/pefile.cs#L118

**Comment by leculver** [comment] 2018-11-19 17:53
Hello!  This issue is being closed due to its age.  The codebase has moved significantly since this was filed.  Please feel free to open a new issue for ClrMD about this issue if it still reproduces on ClrMD 1.0.  (Also, I apologize for having not looked at or resolved this earlier and for resolving it now.  In order for me to be able to make some progress on the growing issue count in ClrMD I need to clear the backlog down to a manageable set of issues, but do feel free to file a new one if this is still a problem.)

**Closed by leculver** 2018-11-19 17:53 UTC
