### ISSUE TITLE
"The method or operation is not implemented." exception when using the Debugger Interface methods

### ISSUE THREAD

**Issue by enkomio** [Microsoft/clrmd#129] opened 2018-11-02 18:30 UTC
Hi,

I'm trying to use _clrmd_ in order to extract specific information from a remote process. When I try to use the methods from the Debugger Interface I receive an exception stating that "The method or operation is not implemented.". I have to say that I used reflection to have access to the internal needed objects, but nevertheless the code should work.

I tried to use the code from the _mdbg_ project and it worked, but that project is pretty old and not maintained, so I would love to use _clrmd_ for all my needs..

This is the code that I wrote for my testing:

	let testDebug(application: String) =
		let pid = System.Diagnostics.Process.Start(application).Id
		System.Threading.Thread.Sleep(5000)
		
		let clrRuntime = DataTarget.AttachToProcess(pid, uint32 5000, AttachFlag.Invasive).ClrVersions.[0].CreateRuntime()    
		let p = clrRuntime.GetType().GetProperty("CorDebugProcess", BindingFlags.NonPublic ||| BindingFlags.Instance)
		let coreDebugProcess = p.GetValue(clrRuntime) :?> ICorDebugProcess 
		let myMethod = getMethod(coreDebugProcess, clrRuntime)

		// get the debugger
		let clrDebuggingType = typeof<ICorDebug>.Assembly.GetType("Microsoft.Diagnostics.Runtime.ICorDebug.CLRDebugging")
		let getDebuggerForProcess = clrDebuggingType.GetMethod("GetDebuggerForProcess", BindingFlags.Static ||| BindingFlags.Public)        
		let args: Object array = [|pid; "v4.0.30319"; null|]
		let corDebug = getDebuggerForProcess.Invoke(null, args) :?> ICorDebug

		// set managed callback
		let managedCallbacks : ICorDebugManagedCallback = upcast new MyManagedCallBack()
		corDebug.SetManagedHandler(managedCallbacks)

		// set the breakpoint
		let breakpoint: ICorDebugFunctionBreakpoint ref = ref(null)        
		myMethod.CreateBreakpoint(breakpoint) // <-- raise the exception "The method or operation is not implemented."

The _myMethod_ variable is of type _ICorDebugFunction_ and this is the (not very clean) code to get it:

	let getMethod(coreDebugProcess: ICorDebugProcess, clrRuntime: ClrRuntime) =
		let tmp = ref(uint32 0)
		let mutable funcFound = false
		let mutable moduloBaseAddress = uint64 0
		let corDebugFunction: ICorDebugFunction ref = ref(null)
				
		let mutable metadataToken = uint32 0
		for o in clrRuntime.Heap.EnumerateObjects() do
			if o.Type <> null && o.Type.Name.Equals("System.Net.NetworkCredential") then
				let m = o.Type.Methods |> Seq.find(fun m -> m.Name.Equals("get_Password"))  
				moduloBaseAddress <- o.Type.Module.ImageBase
				metadataToken <- m.MetadataToken

		let appDomainEnum: ICorDebugAppDomainEnum ref = ref(null)
		coreDebugProcess.EnumerateAppDomains(appDomainEnum)
		let numAppDomains = ref(uint32 0)
		(!appDomainEnum).GetCount(numAppDomains)
		let appDomains = Array.zeroCreate<ICorDebugAppDomain>(int32(!numAppDomains))                
		(!appDomainEnum).Next(uint32(appDomains.Length), appDomains, tmp) |> ignore                                

		appDomains
		|> Array.iter(fun appDomain ->
			let assemblyEnum: ICorDebugAssemblyEnum ref = ref(null)
			appDomain.EnumerateAssemblies(assemblyEnum)
			let numAssemblies = ref(uint32 0)
			(!assemblyEnum).GetCount(numAssemblies)

			let assemblies = Array.zeroCreate<ICorDebugAssembly>(int32(!numAssemblies))
			(!assemblyEnum).Next(uint32(assemblies.Length), assemblies, tmp) |> ignore

			assemblies
			|> Array.iter(fun assembly ->
				let moduleEnum: ICorDebugModuleEnum ref = ref(null)
				assembly.EnumerateModules(moduleEnum)
				let numModules = ref(uint32 0)
				(!moduleEnum).GetCount(numModules)
				
				let modules = Array.zeroCreate<ICorDebugModule>(int32(!numModules))
				(!moduleEnum).Next(uint32(modules.Length), modules, tmp) |> ignore

				modules
				|> Array.iter(fun corModule ->
					if not funcFound then
						try
							let baseAddress = ref(uint64 0)
							corModule.GetBaseAddress(baseAddress)

							if (!baseAddress) = moduloBaseAddress then
								corModule.GetFunctionFromToken(metadataToken, corDebugFunction)
								if (!corDebugFunction) <> null then
									(!corDebugFunction).GetToken(tmp)                            
									funcFound <- true
						with _ ->
							corDebugFunction := null
				)
			)
		)
		!corDebugFunction
		
also, would be very helpful to have some examples that use the _DebuggerInterface_.

**Comment by leculver** [comment] 2018-11-04 17:44
@NoahFalk This looks like a pure ICorDebug question, where ICorDebugFunction::SetBreakpoint returns E_NOTIMPL.  Can you please take this one?

**Comment by noahfalk** [comment] 2018-11-05 23:56
This is probably by design behavior. There are different ways of creating the ICorDebugProcess interface, one for dump debugging and one for live debugging. Clrmd is probably using the dump debugging technique (OpenVirtualProcess API) whereas for live debugging you need to use RegisterForRuntimeStartup https://github.com/dotnet/coreclr/blob/master/src/dlls/dbgshim/dbgshim.cpp#L652

Live debugging on .NET Core requires an in-process helper thread to service IPC requests. These requests are used to implement various debugging operations such as CreateBreakpoint. When given a dump no such thread is available.

Check out https://github.com/dotnet/coreclr/issues/10568 for a little more info on how to set up a live debugging session.

cc @mikem8361

**Comment by leculver** [comment] 2018-11-07 23:35
Since this is more of a question about ICorDebug and not ClrMD, I'm resolving this issue.

**Closed by leculver** 2018-11-07 23:35 UTC
