### ISSUE TITLE
AccessViolationException in ModuleInfo.IsManaged

### ISSUE THREAD

**Issue by discostu105** [Microsoft/clrmd#86] opened 2017-09-25 09:17 UTC
Occasionally, CLRMD would have an access violation with this stack:
```
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.Utilities.PEHeader.FromBuffer(Microsoft.Diagnostics.Runtime.Utilities.PEBuffer buffer, bool virt)	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.Utilities.PEFile.TryLoad(System.IO.Stream stream, bool virt)	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.ModuleInfo.InitData()	Unknown	Non-user code. Cannot find or open the PDB file.
 	Microsoft.Diagnostics.Runtime.dll!Microsoft.Diagnostics.Runtime.ModuleInfo.IsManaged.get()	Unknown	Non-user code. Cannot find or open the PDB file.
>	SuperDump.exe!SuperDump.ModelHelpers.ModelHelpers.ToSDModel(Microsoft.Diagnostics.Runtime.ModuleInfo info) Line 143	C#	Symbols loaded.
 	SuperDump.exe!SuperDump.Analyzers.SystemAnalyzer.GetModuleList() Line 118	C#	Symbols loaded.
 	SuperDump.exe!SuperDump.Analyzers.SystemAnalyzer.InitSystemInfo() Line 29	C#	Symbols loaded.
 	SuperDump.exe!SuperDump.Analyzers.SystemAnalyzer.SystemAnalyzer(SuperDump.DumpContext context) Line 23	C#	Symbols loaded.
 	SuperDump.exe!SuperDump.Program.Main.AnonymousMethod__1() Line 72	C#	Symbols loaded.
 	SuperDump.exe!SuperDump.Program.RunSafe(string name, System.Action action) Line 211	C#	Symbols loaded.
 	SuperDump.exe!SuperDump.Program.Main(string[] args) Line 71	C#	Symbols loaded.

```

For privacy-reasons I cannot share the dump. This happens at a certain type of dumps, but I wasn't able to isolate what makes them different from others.

This particular case, is a full-windows memory dump (6GB) taken with process explorer.

CLRMD version "0.9.170809.3"

(oh, by the way: are the PDB's of Microsoft.Diagnostics.Runtime.dll published anywhere? Is there a symbol server for it? This would make debugging this easier).

**Comment by leculver** [comment] 2018-12-22 19:01
Duplicate of https://github.com/Microsoft/clrmd/issues/159, which is fixed.

**Closed by leculver** 2018-12-22 19:01 UTC
