### ISSUE TITLE
Unable to get some static field values in .NET Core Windows dumps

### ISSUE THREAD

**Issue by chrisnas** [microsoft/clrmd#214] opened 2019-01-18 17:37 UTC
I'm using a code similar to DesktopThreadPool.EnumerateManagedThreadPoolObjects to iterate on the threadpool workitems and tasks. 

```
static void Main(string[] args)
{
    var target = DataTarget.LoadCrashDump(@"D:\dotnet.exe_190118_111215.dmp");
    var runtime = target.ClrVersions[0].CreateRuntime();
    var threadPoolGlobalsType = runtime.Modules.SelectMany(m => m.EnumerateTypes()).Single(t => t.Name == "System.Threading.ThreadPoolGlobals");

    var field = threadPoolGlobalsType.StaticFields.First(f => f.Name == "workQueue");
    var value = field.GetValue(runtime.AppDomains[0]); // null
    var address = field.GetAddress(runtime.AppDomains[0]); // 0

    Console.WriteLine(value);
    Console.ReadLine();
}

```
 [the call to ClrStaticField.GetValue](https://github.com/Microsoft/clrmd/blob/67e34c36107ff09d2e145decfe656b00eaba34e0/src/Microsoft.Diagnostics.Runtime/Desktop/threadpool.cs#L97) fails. Note that GetAddress is also failing.

After a quick debugging session, DesktopStaticField.GetAddress sees the containing type as "shared" and calls V45Runtime.GetDomainLocalModuleById with non null appDomain and id parameters. The call to _sos.GetDomainLocalModuleDataFromAppDomain fails.
I have also tried to use the Shared and System app domain as parameter to the GetValue/GetAddress for the thread pool case but it is not working any better. 

I'm not able to reproduce the problem with a simple type (both static or non static) that contains a static field!
```
static class IamStatic
{
    private static Test _meToo = new Test();

    public static void UseMe()
    {
        Console.WriteLine(_meToo._field);
    }
}

class Test
{
    public uint _field = 0xdeadbeef;
}

```
The only difference I see is the fact that my type is not seen as "shared". 

Note that the .NET Core 2.1 console application used for these tests is creating tasks and workitems before the dump was taken with procdump -ma.

**Comment by leculver** [comment] 2019-01-22 21:59
Thank you for the report!  Unfortunately I'm working on other projects for Microsoft at the moment, but I will take a look at this as soon as I'm back working on ClrMD.

**Comment by chrisnas** [comment] 2019-01-22 22:31
Thanks Lee!
I've found a workaround by scanning the whole heap but it is too "expensive" for our 64 GB linux dumps...
I'll try to dig into SOS to see where the problem could come from (!do is able to show static fields value on .NET Core dumps)

**Comment by leculver** [comment] 2019-01-22 22:49
Without having debugged the issue yet, I would bet the problem is that the code path required to get static variables on .Net Core in some cases is subtly different that what it is on Desktop CLR (and ClrMD hasn't been enlightened to this difference, it uses the Desktop CLR code path).  You should be able to solve this by walking through what functions are called by !do and then by ClrMD, but if you can't figure it out (or just don't want to...) I will take a look as soon as I am able to, but it might be a little while.

Thanks!

**Comment by chrisnas** [comment] 2019-01-22 22:53
This was my plan  :^)
I'll provide feedback as I'll dig into the issue... soon

**Comment by leculver** [comment] 2019-12-03 20:52
Looks like this was fixed in .Net Core.  I'm closing this issue too.  Thanks for the report!

**Closed by leculver** 2019-12-03 20:52 UTC
Labels: bug
