### ISSUE TITLE
DataTarget.ClrVersions crashes when reading live process v0.8.31

### ISSUE THREAD

**Issue by opulos** [Microsoft/clrmd#31] opened 2015-11-04 02:54 UTC
The exact same code, parameters and process work using v0.8.30. So it seems like a new problem.

`DataTarget dataTarget = DataTarget.AttachToProcess(processId, timeoutMillis, attachFlag);`

ProcessId is process to a running .NET program.
timeoutMillis = 5000
attachFlag = Passive

Then accessing dataTarget.ClrVersions crashes on this line:
`if (ReadMemory(moduleBase + 0x3c, buffer, buffer.Length, out read) && read == buffer.Length)`

Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

 `at Microsoft.Diagnostics.Runtime.LiveDataReader.GetFileProperties(UInt64 moduleBase, UInt32& filesize, UInt32& timestamp) in c:\Microsoft\clrmd\Microsoft.Diagnostics.Runtime\datatarget.cs:line 2522
   at Microsoft.Diagnostics.Runtime.LiveDataReader.EnumerateModules() in c:\Microsoft\clrmd\Microsoft.Diagnostics.Runtime\datatarget.cs:line 2378
   at Microsoft.Diagnostics.Runtime.DataTargetImpl.InitModules() in c:\Microsoft\clrmd\Microsoft.Diagnostics.Runtime\datatarget.cs:line 1372
   at Microsoft.Diagnostics.Runtime.DataTargetImpl.EnumerateModules() in c:\Microsoft\clrmd\Microsoft.Diagnostics.Runtime\datatarget.cs:line 1350
   at Microsoft.Diagnostics.Runtime.DataTargetImpl.get_ClrVersions() in c:\Microsoft\clrmd\Microsoft.Diagnostics.Runtime\datatarget.cs:line 1220`

Let me know if you need more information, or would like to see the error in action via a join.me meeting. I can host the meeting.

**Comment by opulos** [comment] 2015-11-04 03:01
Note: This error occurs when using the source code zip you provided in your latest post. However, it seems the error does not occur when using the DLL from nuget.

**Comment by leculver** [comment] 2015-11-04 18:55
Thank you for the bug report!  I will not be able to take a look until this weekend, but I'll be sure it's fixed asap, and certainly before publishing a NuGet package.

**Comment by leculver** [comment] 2018-11-19 17:51
Hello!  This issue is being closed due to its age.  The codebase has moved significantly since this was filed.  Please feel free to open a new issue for ClrMD about this issue if it still reproduces on ClrMD 1.0.  (Also, I apologize for having not looked at or resolved this earlier and for resolving it now.  In order for me to be able to make some progress on the growing issue count in ClrMD I need to clear the backlog down to a manageable set of issues, but do feel free to file a new one if this is still a problem.)

**Closed by leculver** 2018-11-19 17:51 UTC
