### ISSUE TITLE
Using newer .Net .dlls 

### ISSUE THREAD

**Issue by DianaKoenraadt** [Microsoft/clrmd#39] opened 2016-02-12 08:25 UTC
I've made some memory dumps on my local machine, which has .Net 4.6
However, when reading these memory dumps, the version reported is 4.0.30319.34209 because the application is a .Net 4 application.

Due to the reported version being different than the .dlls present on my machine, I cannot use mscordacwks.dll from my machine. However, I feel this should be possible, as it is the same machine on which the dumps were made.

So, in this case, would it be possible to use the .Net 4.6 .dlls from the machine itself to analyze the memory dumps?

**Comment by leculver** [comment] 2018-11-19 17:52
Hello!  This issue is being closed due to its age.  The codebase has moved significantly since this was filed.  Please feel free to open a new issue for ClrMD about this issue if it still reproduces on ClrMD 1.0.  (Also, I apologize for having not looked at or resolved this earlier and for resolving it now.  In order for me to be able to make some progress on the growing issue count in ClrMD I need to clear the backlog down to a manageable set of issues, but do feel free to file a new one if this is still a problem.)

**Closed by leculver** 2018-11-19 17:52 UTC
