### ISSUE TITLE
ClrThread.StackTrace memory leak

### ISSUE THREAD

**Issue by stjeong** [Microsoft/clrmd#47] opened 2016-08-19 07:02 UTC
To repro, I just write a program like this,

```
while (true)
            {
                using (DataTarget target = DataTarget.AttachToProcess(
                                                            Process.GetCurrentProcess().Id, 5000, AttachFlag.Passive))
                {
                    ClrRuntime runtime = target.ClrVersions.First().CreateRuntime();
                    foreach (ClrThread thread in runtime.Threads)
                    {
                        IList<ClrStackFrame> stackFrames = thread.StackTrace;
                    }
                    runtime.Flush();
                }
            }`
```

about 50MB leaks per every seconds.

**Comment by Zero3** [comment] 2017-03-23 20:46
I'm also seeing a memory leak doing almost exactly what you posted :/.

**Comment by leculver** [comment] 2018-11-19 17:54
Hello!  This issue is being closed due to its age.  The codebase has moved significantly since this was filed.  Please feel free to open a new issue for ClrMD about this issue if it still reproduces on ClrMD 1.0.  (Also, I apologize for having not looked at or resolved this earlier and for resolving it now.  In order for me to be able to make some progress on the growing issue count in ClrMD I need to clear the backlog down to a manageable set of issues, but do feel free to file a new one if this is still a problem.)

**Comment by leculver** [comment] 2018-11-19 20:42
I found the issue, unfortunately it's difficult to work around.  The underlying problem is that this `if` block is missing on Desktop CLR:

https://github.com/dotnet/coreclr/blob/75890669d59ea8e1a28ade8222ebec2706082674/src/debug/daccess/task.cpp#L370

I will file an internal bug about this and try to get it fixed in Desktop CLR.  Unfortunately I don't plan to fix this in ClrMD unless there's no fix for it in CLR 4.8.

**Closed by leculver** 2018-11-19 20:42 UTC

**Comment by leculver** [comment] 2018-11-19 21:06
Actually I've found a really ugly workaround and submitted it as https://github.com/Microsoft/clrmd/commit/acd72689f3f7aade4b75da2a3bc3e6869b0ec16d.  This will be fixed in ClrMD 1.0

**Comment by Zero3** [comment] 2020-01-28 10:12
I noticed the following .NET Framework bugfix (from https://devblogs.microsoft.com/dotnet/net-framework-january-preview-of-quality-rollup/):

> There is a race condition in the portable PDB metadata provider cache that leaked providers and caused crashes in the diagnostic StackTrace API. To fix the race, detect the cause where the provider wasn’t being disposed and dispose it.

Maybe that is related to this issue?

**Comment by leculver** [comment] 2020-01-28 17:26
This is unrelated, we don't use that area of the runtime in ClrMD.

AFAIK the most recent versions of ClrMD 1.1 and 2.0 should not be affected by this issue.
