### ISSUE TITLE
TryGetDacLocation not found

### ISSUE THREAD

**Issue by rvmaccount** [Microsoft/clrmd#42] opened 2016-04-02 15:56 UTC
Per the getting started example, CLRInfo has a method named TryGetDacLocation however from the latest version this method is missing.

Usage in the sample 

 string dacLocation = version.TryGetDacLocation();

Instead ClrInfo .LocalMatchingDac property should be used.

**Comment by leculver** [comment] 2018-11-19 17:53
Hello!  This issue is being closed due to its age.  The codebase has moved significantly since this was filed.  Please feel free to open a new issue for ClrMD about this issue if it still reproduces on ClrMD 1.0.  (Also, I apologize for having not looked at or resolved this earlier and for resolving it now.  In order for me to be able to make some progress on the growing issue count in ClrMD I need to clear the backlog down to a manageable set of issues, but do feel free to file a new one if this is still a problem.)

**Closed by leculver** 2018-11-19 17:53 UTC
