### ISSUE TITLE
Finding the offset for native symbol

### ISSUE THREAD

**Issue by raffaeler** [microsoft/clrmd#753] opened 2020-06-11 12:25 UTC
I am referring to [this thread](https://github.com/dotnet/runtime/issues/11157) to find which ALC (AssemblyLoadContext) is hosting a ClrObject which is (IMO) a fundamental scenario in .NET Core.
As shown in that thread, the ALC can be retrieved only following a couple of native pointers in the vtable of two native classes.

I was successful in using ClrMD to get the needed information, but unfortunately I had to hardcode the two offset of the native vtable.
For this reason I would like to:
1. given a memory address pointing to an instance of a native (c++) class, getting its pdb
2. obtain from the pdb the offset, given the name of the member field.

I tried to enumerate the modules and getting the pdbs, but it looks like the native side is not accessible from there.
Hints?

**Comment by NextTurn** [comment] 2020-06-11 12:53
A built-in PDB reader has been removed in 2.0 and it's unlikely that we'll have a new one in ClrMD's core library.

**Comment by raffaeler** [comment] 2020-06-11 12:59
Got it. 
As far as I know PDBs must be in Portable format to be accessed cross-platform. I guess this is the reason for that decision.
As long as the PDB is in portable format, ho can I get the module and the symbol file to use an external PDB reader?

**Comment by NextTurn** [comment] 2020-06-11 13:05
how can I get the module and the symbol file to use an external PDB reader?

Not sure if this answers your question. [`PEImage.DefaultPdb`](https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs#L169) can provide information about the PDB file and [`DataTarget.BinaryLocator`](https://github.com/microsoft/clrmd/blob/17bea31ca88e89ec695b2b2073eb9b61cc425e6e/src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs#L48) can help to download the PDB from a symbol server.

**Comment by raffaeler** [comment] 2020-06-11 13:07
I already tried but `PEImage` throws an first-chance `NullReferenceException` and later always returns null.

**Comment by NextTurn** [comment] 2020-06-11 13:09
Well, every time you see a `NullReferenceException` there must be a bug somewhere. Could you show the stack trace?

**Comment by raffaeler** [comment] 2020-06-11 13:23
Logged this issue, easy to fix. I can do it, but I have an outstanding PR, so I will wait before creating another branch.
https://github.com/microsoft/clrmd/issues/754

**Comment by weltkante** [comment] 2020-06-11 13:25
> As far as I know PDBs must be in Portable format to be accessed cross-platform.

Are you sure C/C++ code produces portable PDBs? I thought only Roslyn (and other managed compilers) did ...

**Comment by raffaeler** [comment] 2020-06-11 13:41
@weltkante afaik portable pdbs are .net core only.
I was just trying to guess the reason why the pdb reader was removed. In fact I wrote about using an external reader.

**Comment by leculver** [comment] 2020-06-11 20:35
I think this question was answered, so I'm closing, please let me know if there are still open questions here.

In short:  ClrMD doesn't have a PDB Reader by design now, but you could add one of the existing ones out there to your project.  ClrMD doesn't support reading native offsets, so in order for you to accomplish what's outlined in https://github.com/dotnet/runtime/issues/11157 you will need to either ask the runtime team to add a dac function which ClrMD can consume, or you have to download coreclr.pdb and open it with a PDB reading library.

**Closed by leculver** 2020-06-11 20:35 UTC
