### ISSUE TITLE
ClrMD 2 EnumerateReferences much slower than ClrMD 1.1

### ISSUE THREAD

**Issue by jwdj** [microsoft/clrmd#660] opened 2020-05-12 14:25 UTC
For calculating the retention size of objects I use ClrMD 1.1 to visit all objects in a depth first search.
Out of curiositity I tried the beta version (2.0.0-beta.20230.2). Some code needed to be rewritten slightly but I like the API improvements.
But the performance of processing the same dump file was about 5 times slower.
I know that 2.0 is not finished yet, but before releasing 2.0 it would be wise to compare against ClrMD 1.1 visiting all objects and retrieving shallow size.

**Comment by NextTurn** [comment] 2020-05-12 15:06
I'd like to look into this but I need some guidance on performance profiling with *dotnet-trace*... :(

**Comment by jwdj** [comment] 2020-05-12 18:20
I recommend using [PerfView](https://github.com/Microsoft/perfview/releases). After recording a trace, you can go to the Flamegraph tab to see which methods take the most time. 
Here is an online [tutorial](https://mattwarren.org/2020/03/03/Analysing-.NET-Runtime-Startup-with-Flamegraphs/).
The traces are to big to send so I will try to summarize where more time is spent than before. This might take some time...

**Comment by jwdj** [comment] 2020-05-12 19:54
Well, the traces between ClrMD1.1 and ClrMD2.0 are very different. Hard to compare apples to apples. What I can tell is that ClrMD 2.0 suffers from I/O related slowdown. 83% is spent on reading the dump file. About 6% on my own code. So 11% on other ClrMD methods.
Samples spent in 1.1: 35893
Samples spent in 2.0: 155506

Here the methods that take the most time:
83%   microsoft.diagnostics.runtime!Microsoft.Diagnostics.Runtime.Windows.MinidumpMemoryReader.Read(unsigned int64,value class System.Span`1<unsigned int8>,int32&) (63809 inclusive samples, 37.88%)
63.8% microsoft.diagnostics.runtime!Microsoft.Diagnostics.Runtime.SpanExtensions.Read(class System.IO.Stream,value class System.Span`1<unsigned int8>)
60,7% mscorlib.ni!System.IO.FileStream.Read(Byte[], Int32, Int32)
17%   mscorlib.ni!System.IO.FileStream.set_Position(Int64)

**Comment by drewnoakes** [comment] 2020-05-13 01:43
@jwdj were you running this on .NET Framework?

https://adamsitnik.com/Span/#slow-vs-fast-span

**Comment by NextTurn** [comment] 2020-05-13 02:18
https://github.com/microsoft/clrmd/blob/b49054de819ecb58f07b835434f5834a0a619ab2/src/Microsoft.Diagnostics.Runtime/src/Extensions/SpanExtensions.cs#L26

It's probably caused by double copying on .NET FX due to `Stream.Read(Span<byte>)` not available. This would be a nightmare for file I/O because ClrMD 2.0 is completely span-based.

**Comment by jwdj** [comment] 2020-05-13 07:25
@drewnoakes Yes this was running from .NET Framework. From [LINQPad 5](https://www.linqpad.net/LINQPad5.aspx) to be precise (32 bits version).
@NextTurn I agree that spans on .NET Framework can't be the problem. I think CLRMD 2 caches a lot less. It uses a lot less memory in any case (that is good!). Maybe some kind of buffering could help, or memory mapped I/O as you suggested yourself.

**Comment by leculver** [comment] 2020-05-13 16:30
I've not finished perf testing yet, which I have on the roadmap here: https://github.com/microsoft/clrmd/issues/614.

> For calculating the retention size of objects I use ClrMD 1.1 to visit all objects in a depth first search.

@jwdj Can you please give me the code snippet you are seeing a 5x slowdown on to make sure I understand?  I assume you are using something like `ClrObject.EnumerateReferences` recursively?  If so this is a known issue that I intend to fix in the perf testing outlined by #614.  Here is the root cause:

We have a memory reader that we read the heap in large chunks when enumerating objects:
https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdSegment.cs#L76
 
But EnumerateReferences isn't reading from that cache (and it should be, clrmd 1.1 reads from the cached memory):
https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs#L236

Please do continue to report perf issues though (hopefully along with a mini snippet to reproduce it).  I'll be tackling them as soon as I'm back to work on ClrMD.  I'm currently working on some high priority issues for the rest of the week.

**Comment by jwdj** [comment] 2020-05-14 08:43
Thank you @leculver for taking the time to investigate this issue regarding the fact that your time is needed elsewhere. I'm perfectly fine with using ClrMD 1.1 in the meantime. It helped me find the objects in our software that take the most memory and realizing that some optimizations would be futile considering the enormous size of ResourceDictionaries.

Here the code I used for the ClrMD 2 version.
It should probably be better to use `ClrObject.EnumerateReferences` since the type is now determined more than once. In ClrMD 1.1 I used `type.EnumerateRefsOfObject` taken from the [ObjSize example](https://github.com/microsoft/dotnet-samples/blob/master/Microsoft.Diagnostics.Runtime/CLRMD/docs/WalkingTheHeap.md) 

```c#
private IEnumerable<(ulong address, ClrType type, int dfsIndex)> IterateDepthFirst(bool createVirtualRoot, Action<ulong, int, ulong> referencedBy)
{
	var eval = new Stack<uint>(83 * 256);
	ObjectSet considered = null;

	if (!Heap.CanWalkHeap)
		yield break;

	int dfsIndex = 0;

	if (createVirtualRoot)
		yield return (0, null, ++dfsIndex);

	considered = new ObjectSet(Heap);
	foreach (var address in RootedObjects)
	{
		referencedBy?.Invoke(0, dfsIndex, address);
		if (considered.Contains(address))
			continue;

		considered.Add(address);
		eval.Push(AddressToInt(address));
	}
	considered.Clear();
	while (eval.Count > 0)
	{
		ulong address = IntToAddress(eval.Pop());
		if (considered.Contains(address))
			continue;

		considered.Add(address);

		// Grab the type. We will only get null here in the case of heap corruption.
		var type = Heap.GetObjectType(address);
		if (type == null)
			continue;

		yield return (address, type, ++dfsIndex);

		// Now enumerate all objects that this object points to, add them to the
		// evaluation stack if we haven't seen them before.
		foreach (var child in Heap.EnumerateObjectReferences(address, type, false, true))
		{
			if (child.Address != 0)
			{
				if (!considered.Contains(child.Address))
				{
					eval.Push(AddressToInt(child.Address));
				}
				referencedBy?.Invoke(address, dfsIndex, child.Address);
			}
		}
	}
}

private int _addressShift = IntPtr.Size == 4 ? 2 : 3;

public uint AddressToInt(ulong address)
{
	address = address >> _addressShift;
	if (address <= uint.MaxValue)
		return (uint)address;

	throw new ArgumentOutOfRangeException(nameof(address));
}

public ulong IntToAddress(uint i) => i << _addressShift;
```

**Comment by NextTurn** [comment] 2020-05-14 14:57
@jwdj Do you have time to try #661 and see if it somewhat makes ClrMD faster? Your scenario makes much more sense than my unrealistic ad-hoc tests.

The CI artifacts are available [here](https://dev.azure.com/dnceng/public/_build/results?buildId=644493&view=artifacts).

**Comment by jwdj** [comment] 2020-05-15 14:18
@NextTurn Not sure what you want me to do with the CI artifacts. Some binlog files and a props file. I expected to find a .nupkg.

**Comment by NextTurn** [comment] 2020-05-15 14:23
Odd. @leculver Where are the Nuget packages for automated CI runs? They are not [here](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools&package=Microsoft.Diagnostics.Runtime&protocolType=NuGet&version=2.0.0-beta.20264.1&view=versions) either.

**Comment by leculver** [comment] 2020-05-18 23:15
I'm not sure either.  We can just ship the change in pre-release and use the real nuget packages.

**Comment by leculver** [comment] 2020-05-26 22:51
@jwdj Thank you for this report!  I've gotten to the bottom of the issue here which is (mostly) around .

The first issue is as I described, we need to put a memory read cache around enumerating an individual object's data.  This is easily fixable and should put us back into line with ClrMD 1.1's performance.

The second issue I've been looking at is the fact that a lot of the reads aren't localized and require too many tiny reads.  For example, when we read the methodtable for an object to create the ClrObject we should try to read enough data that we don't need do a second memory read to enumerate its references.

I'll fix the first issue shortly, and when we are back within ClrMD 1.1's performance I'll close this issue.  I'm still thinking about the second issue.  We might want to have a ClrObject.EnumerateTransitiveClosure which efficiently walks objects very carefully to minimize reads.  I'll let you know what I come up with.

**Comment by leculver** [comment] 2020-05-27 01:29
@jwdj Can you please give this nuget package a try?

https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.0-beta.20276.4

This implemented the bare minimum of improvements here.  I still have work to do to make this better but I wanted to see if this helped your scenario or if I have a lot more work to do?

**Comment by jwdj** [comment] 2020-05-27 08:10
@leculver @NextTurn : Well there is certainly an improvement over the results from yesterday using the previous beta version. Thank you for that. Here the results for a dump file of 600 MB (628,368,104 bytes)

| Version | Memory used | Total allocated | Time |
| --- | --- | --- | --- |
| 1.1.126102 | 96,461 KB | 544,730 KB | 00:00:06.0136100 |
| beta.20273.1 | 30,681 KB | 410,931 KB | 00:00:24.2071408 |
| beta.20276.4 | 31,580 KB | 408,346 KB | 00:00:16.6063535 |

I really like the improvements in memory usage over ClrMD 1.1 (part of this memory are my own structures so the difference is even bigger)

Maybe you can speed it up with the improvement @chrisnas [proposed](https://labs.criteo.com/2018/08/how-to-beat-dumpheap-stat-with-clrmd/)?

**Comment by NextTurn** [comment] 2020-05-27 08:29
@jwdj Thanks for following up! I'm a bit curious about how the [2.0.0-beta.20276.1](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools&package=Microsoft.Diagnostics.Runtime&protocolType=NuGet&version=2.0.0-beta.20276.1&view=overview) package would behave as well. Could you give it a try?

**Comment by NextTurn** [comment] 2020-05-27 08:42
> Maybe you can speed it up with the improvement @chrisnas [proposed](https://labs.criteo.com/2018/08/how-to-beat-dumpheap-stat-with-clrmd/)?

This should have been implemented. You can find the type cache dictionary here:

https://github.com/microsoft/clrmd/blob/e1f4d31d2dc55dd2e67f7b4fd4b9959a30039f22/src/Microsoft.Diagnostics.Runtime/src/Builders/RuntimeBuilder.cs#L44

**Comment by leculver** [comment] 2020-05-27 16:58
> Well there is certainly an improvement over the results from yesterday using the previous beta version. Thank you for that. Here the results for a dump file of 600 MB (628,368,104 bytes)

Thank you for doing some measurements!  I had hoped my changes would have bigger impact, but I knew there was a lot more work to do here.  I'm actively working on this issue and should hopefully have a better solution by the end of the week.

**Comment by leculver** [comment] 2020-05-27 19:08
Ok I've gotten to the bottom of this.  The underlying problem here is that Stream.Read is orders of magnitude slower than what DbgEng does to read memory (this measurement is without #661).  Note that DbgEng is the default reader in 1.1.  Here's what this looks like for an objsize test reading 24 million objects in an x86 process:

| Version | # Reads | Bytes Read | Seconds | Reads/sec | Bytes/sec |
| --- | --- | --- | --- | ---| --- |
| ClrMD1.1 | 47,142,183 | 140,301,455,323 | 88.2747374 | 534,039.35 | 1,589,372,672.81 |
| ClrMD2.0 | 76,447,020 | 868,825,679 | 340.2674627 | 224,667.44 | 2,553,361.03 |

Basically ClrMD 2.0 calls into ReadMemory 62% more times, but only reads 1% of the data from the underlying file.

To fix this, @ryanmolden is generously donating the data reader implementation he's been working on for a while.  His data reader already does what I was planning to do (essentially caching a lot more instead of doing direct Stream.Read seeks).  This should greatly improve perf.  He's also implemented [AWE](https://docs.microsoft.com/en-us/windows/win32/memory/address-windowing-extensions) support if your machine has it enabled, which greatly improves performance for large dumps and reads.

I'll be plumbing through his data reader implementations this week and we'll reevaluate where we are.

**Comment by leculver** [comment] 2020-05-28 01:35
I have most of the solution coded up here.  It will be done in another day or two:  https://github.com/leculver/clrmd/tree/aweMemoryReader

You can set a max "cache size" for data cached from a minidump.  Then we will go down a few different codepaths depending on the size of the dump:

1.  If the dump size is smaller than the cache size we'll just load the whole file with MemoryMappedFile and read from that.  This is "Uncached" in the table below.
2.  If the dump is larger than your cache size and you set a size too small for us to take advantage of caching data (e.g. in a low memory scenario), we'll default to the current behavior which is slow but doesn't take up any extra memory.  The threshold for this defaults to 32 megs, but it will be configurable.
3.  If you specified a reasonable sized cache (32 megs or greater) we'll page the dump into memory using two strategies, either using AWE or with byte arrays depending on whether you have AWE enabled.  By default AWE is disabled for all users in windows.  This is "ArrayPool" and "AWE" in the table below.

Here's a rough test I ran running the above algorithm on 23 million objects.  It's not super accurate but it's ballpark correct:

| Method | Time |
| --- | --- |
| DbgEng | 70 seconds |
| Uncached | 340 seconds |
| ArrayPool | 75 seconds |
| AWE | 47 seconds |

Long story short, the "default" behavior for large dumps will be "ArrayPool" cache which is _slightly_ slower than what ClrMD 1.1.  About an 8% regression or so, and that's good enough for RTM.  At a later date we _might_ be able to reduce that regression if we dig deeply and see if the implementation can be improved.  However, if you turn on AWE you will see **noticeably** better performance, 33% faster.

FYI, you can turn on AWE by going to gpedit.msc  and enabling `Computer Configuration -> Windows Settings -> Security Settings -> Local Policies -> User Rights Assignment -> Lock Pages in Memory` for the current user (then reboot).  I'll include some documentation for this when we release.  This feature will simply light up in ClrMD without you needing to do anything if you have AWE enabled.

**Closed** 2020-05-28 19:24 UTC
Labels: bug

**Comment by leculver** [comment] 2020-05-28 21:56
The fix for this is published here:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.0-rc.20278.6

As a reminder I expect this build to be within 10% of ClrMD 1.1 but still a little slower.  I do plan to revisit the reader's perf at some point.  Please let me know if this is still significantly slower in your scenario.

**Comment by jwdj** [comment] 2020-06-02 06:30
@leculver Well this is definitely a big improvement in speed. Even better than ClrMD 1.1 and without AWE. Memory usage has logically gone up though.
Thank you for your effort addressing this issue.

| Version | Memory used | Total allocated | Time |
|---|---:|---:|---:|
| 1.1.126102 | 96,461 KB | 544,730 KB | 00:00:06.0136100 |
| beta.20276.4 | 31,580 KB | 408,346 KB | 00:00:16.6063535 |
| rc.20278.6 | 136,443 KB | 562,422 KB | 00:00:04.9473435 |

**Comment by leculver** [comment] 2020-06-02 15:48
Thanks to @ryanmolden who donated these implementations.  I only adapted the code for ClrMD.

> Memory usage has logically gone up though.

@jwdj Yep, unfortunately baseline memory did go up.  I will say it's not a goal for ClrMD 2.0 to have lower memory usage than 1.1 by default.  Instead the intent is to let the user have a finer control over how much memory ClrMD is allowed to use.  If there's too much memory used, please be sure to look at the [CacheOptions](https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/Common/CacheOptions.cs) class.   On x86 by default we reserve 0x800_00000 bytes (128 megs) for caching the heap.

Users are welcome to set that all the way down to 0 if they like, but below a certain point we will default back to the previous uncached Stream.Read implementation.  The idea is the user should be able to tune ClrMD to their scenario.

**Comment by chrisnas** [comment] 2020-06-08 14:54
Thanks for the release @leculver!
I planned to start my first tests last week as you asked for but unexpected investigation came up... So I'm only able to start testing today with a simple count of strings in a 64 bit heap of a 20 GB dump file and I still see large (**x4**!!) difference between 1.1 and 2.0 in term of duration (and size but expected with the new cache mechanism that goes up to 4GB).

Here are my results for 3 runs in a raw by the same 64 .NET Core application
Execution time in   ms | Gen0 | Gen1 | Gen2 |   | Execution time in   ms | Gen0 | Gen1 | Gen2
-- | -- | -- | -- | -- | -- | -- | -- | --
32794 | 232 | 8 | 3 |   | 149329 | 26 | 17 | 10
31653 | 232 | 2 | 3 |   | 147071 | 41 | 20 | 6
30537 | 228 | 2 | 2 |   | 146827 | 18 | 10 | 6

Here is the code (_heap is retrieved from the ClrRuntime of the dump and stringType is the ClrType associated to System.String):
**1.1**
```
foreach (var address in _heap.EnumerateObjectAddresses())
{
    try
    {
        var objType = _heap.GetObjectType(address);
        if (objType == null)
            continue;
        result.objCount++;

        if (objType != stringType)
            continue;
        result.strCount++;
    }
    catch (Exception x)
    {
        // some InvalidOperationException seems to occur 
    }
}
```


**2.0**
```
foreach (var obj in _heap.EnumerateObjects())
{
    try
    {
        var objType = obj.Type;
        if (objType == null)
            continue;
        result.objCount++;

        if (objType != stringType)
            continue;
        result.strCount++;
    }
    catch (Exception x)
    {
        // some InvalidOperationException seems to occur
    }
}
```

But what scares me the most is the fact that the count results are very different!
1.1: Objects: 45943693 | Strings: 6203332
2.0: Objects: 63114925 | Strings: 8160077

I can get that retrieving an object type works "better" in 2.0 so less null types but I don't get why the string count could be different...

Let me know if you would need more tests or details

**Comment by leculver** [comment] 2020-06-08 17:37
@chrisnas I just opened https://github.com/microsoft/clrmd/issues/743, would you mind posting updates there?  There's a lot of feedback all over the place so it would help me not miss any questions or feedback. =)

Happy to keep chatting here and always feel free to open a new issue, but I'm worried I'll miss a message here.

> I can get that retrieving an object type works "better" in 2.0 so less null types but I don't get why the string count could be different...

It's entirely possible that the new code fixes bugs we didn't even know existed in the old code.  One place that I know of that we fixed heap walking issues is x86 when /3gb+ is enabled.  We had a lot of sign extension issues on x86, but none of that should have affected x64 processes.

Keep in mind ClrMD 2.0 is _almost_ a complete rewrite of the core of the library so we _hopefully_ fixed a lot of nonsense due to 8 years of bad architecture.

**Comment by chrisnas** [comment] 2020-06-09 07:26
I just tried to find the "right" place for this @leculver  :^)
I'll create a bug next time (if a non closed one does not exist) to make it easier for you to follow-up

**Comment by leculver** [comment] 2020-06-09 16:17
@chrisnas No worries!  I just wanted to make 100% sure I didn't miss anything.  =)
